<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use RuntimeException;

class Stage3SearchDemoListingsSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            $userId = DB::table('users')->orderBy('id')->value('id');

            if (!$userId) {
                throw new RuntimeException('No user exists. Seed/create a user first.');
            }

            $rows = [
            [
                'title' => 'شقة للإيجار في حدة',
                'description' => 'شقة عائلية حديثة قريبة من الخدمات في حدة.',
                'purpose' => 'rent',
                'type' => 'apartment',
                'price' => 220000,
                'currency' => 'YER',
                'area_m2' => 145,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'address' => 'حدة، صنعاء',
                'latitude' => 15.3448000,
                'longitude' => 44.1838000,
            ],
            [
                'title' => 'شقة للبيع في شارع الستين',
                'description' => 'شقة واسعة للبيع بالقرب من شارع الستين.',
                'purpose' => 'sale',
                'type' => 'apartment',
                'price' => 48000000,
                'currency' => 'YER',
                'area_m2' => 165,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'address' => 'شارع الستين، صنعاء',
                'latitude' => 15.3619000,
                'longitude' => 44.1735000,
            ],
            [
                'title' => 'شقة للإيجار في سعوان',
                'description' => 'شقة مرتبة بإطلالة مفتوحة في سعوان.',
                'purpose' => 'rent',
                'type' => 'apartment',
                'price' => 160000,
                'currency' => 'YER',
                'area_m2' => 120,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'address' => 'سعوان، صنعاء',
                'latitude' => 15.3898000,
                'longitude' => 44.2216000,
            ],
            [
                'title' => 'شقة للبيع في بيت بوس',
                'description' => 'شقة جديدة ضمن مبنى سكني هادئ في بيت بوس.',
                'purpose' => 'sale',
                'type' => 'apartment',
                'price' => 39000000,
                'currency' => 'YER',
                'area_m2' => 135,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'address' => 'بيت بوس، صنعاء',
                'latitude' => 15.3079000,
                'longitude' => 44.1752000,
            ],
            [
                'title' => 'شقة للإيجار في شملان',
                'description' => 'شقة مناسبة للعائلات وقريبة من الخط العام.',
                'purpose' => 'rent',
                'type' => 'apartment',
                'price' => 140000,
                'currency' => 'YER',
                'area_m2' => 110,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'address' => 'شملان، صنعاء',
                'latitude' => 15.4212000,
                'longitude' => 44.1489000,
            ],
            [
                'title' => 'شقة للبيع في مذبح',
                'description' => 'شقة اقتصادية للبيع في منطقة مذبح.',
                'purpose' => 'sale',
                'type' => 'apartment',
                'price' => 31500000,
                'currency' => 'YER',
                'area_m2' => 125,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'address' => 'مذبح، صنعاء',
                'latitude' => 15.3796000,
                'longitude' => 44.1667000,
            ],
            [
                'title' => 'منزل للبيع في بيت معياد',
                'description' => 'منزل مستقل مع حوش وموقف سيارة.',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 125000000,
                'currency' => 'YER',
                'area_m2' => 280,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'address' => 'بيت معياد، صنعاء',
                'latitude' => 15.3207000,
                'longitude' => 44.1981000,
            ],
            [
                'title' => 'منزل للإيجار في حزيز',
                'description' => 'منزل عائلي للإيجار قريب من الخدمات.',
                'purpose' => 'rent',
                'type' => 'house',
                'price' => 350000,
                'currency' => 'YER',
                'area_m2' => 240,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'address' => 'حزيز، صنعاء',
                'latitude' => 15.2928000,
                'longitude' => 44.2079000,
            ],
            [
                'title' => 'منزل للبيع في دار سلم',
                'description' => 'منزل دورين للبيع في دار سلم.',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 98000000,
                'currency' => 'YER',
                'area_m2' => 260,
                'bedrooms' => 5,
                'bathrooms' => 3,
                'address' => 'دار سلم، صنعاء',
                'latitude' => 15.2814000,
                'longitude' => 44.1934000,
            ],
            [
                'title' => 'منزل للإيجار في عصر',
                'description' => 'منزل هادئ مع مساحة خارجية في عصر.',
                'purpose' => 'rent',
                'type' => 'house',
                'price' => 300000,
                'currency' => 'YER',
                'area_m2' => 230,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'address' => 'عصر، صنعاء',
                'latitude' => 15.3701000,
                'longitude' => 44.1432000,
            ],
            [
                'title' => 'منزل للبيع في الروضة',
                'description' => 'منزل سكني قريب من المدارس والخدمات.',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 112000000,
                'currency' => 'YER',
                'area_m2' => 250,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'address' => 'الروضة، صنعاء',
                'latitude' => 15.4014000,
                'longitude' => 44.2071000,
            ],
            [
                'title' => 'فيلا للبيع في حدة',
                'description' => 'فيلا فاخرة بمدخل مستقل وحديقة صغيرة.',
                'purpose' => 'sale',
                'type' => 'villa',
                'price' => 320000000,
                'currency' => 'YER',
                'area_m2' => 420,
                'bedrooms' => 6,
                'bathrooms' => 6,
                'address' => 'حدة، صنعاء',
                'latitude' => 15.3422000,
                'longitude' => 44.1781000,
            ],
            [
                'title' => 'فيلا للإيجار في شارع الخمسين',
                'description' => 'فيلا مناسبة للسكن العائلي أو الدبلوماسي.',
                'purpose' => 'rent',
                'type' => 'villa',
                'price' => 900000,
                'currency' => 'YER',
                'area_m2' => 390,
                'bedrooms' => 5,
                'bathrooms' => 5,
                'address' => 'شارع الخمسين، صنعاء',
                'latitude' => 15.3359000,
                'longitude' => 44.1895000,
            ],
            [
                'title' => 'فيلا للبيع في بيت بوس',
                'description' => 'فيلا حديثة التشطيب في بيت بوس.',
                'purpose' => 'sale',
                'type' => 'villa',
                'price' => 245000000,
                'currency' => 'YER',
                'area_m2' => 360,
                'bedrooms' => 5,
                'bathrooms' => 5,
                'address' => 'بيت بوس، صنعاء',
                'latitude' => 15.3098000,
                'longitude' => 44.1696000,
            ],
            [
                'title' => 'فيلا للإيجار في فج عطان',
                'description' => 'فيلا بإطلالة جبلية وموقع هادئ.',
                'purpose' => 'rent',
                'type' => 'villa',
                'price' => 750000,
                'currency' => 'YER',
                'area_m2' => 340,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'address' => 'فج عطان، صنعاء',
                'latitude' => 15.3528000,
                'longitude' => 44.1546000,
            ],
            [
                'title' => 'أرض للبيع في شملان',
                'description' => 'قطعة أرض سكنية على شارع فرعي قريب من الخدمات.',
                'purpose' => 'sale',
                'type' => 'land',
                'price' => 85000000,
                'currency' => 'YER',
                'area_m2' => 300,
                'bedrooms' => null,
                'bathrooms' => null,
                'address' => 'شملان، صنعاء',
                'latitude' => 15.4255000,
                'longitude' => 44.1532000,
            ],
            [
                'title' => 'أرض للبيع في بيت زبطان',
                'description' => 'أرض مناسبة للبناء والاستثمار.',
                'purpose' => 'sale',
                'type' => 'land',
                'price' => 72000000,
                'currency' => 'YER',
                'area_m2' => 260,
                'bedrooms' => null,
                'bathrooms' => null,
                'address' => 'بيت زبطان، صنعاء',
                'latitude' => 15.4068000,
                'longitude' => 44.1784000,
            ],
            [
                'title' => 'أرض للبيع في دار سلم',
                'description' => 'أرض سكنية بسعر مناسب في دار سلم.',
                'purpose' => 'sale',
                'type' => 'land',
                'price' => 56000000,
                'currency' => 'YER',
                'area_m2' => 240,
                'bedrooms' => null,
                'bathrooms' => null,
                'address' => 'دار سلم، صنعاء',
                'latitude' => 15.2847000,
                'longitude' => 44.1882000,
            ],
            [
                'title' => 'أرض للبيع في أرتل',
                'description' => 'أرض على مخطط سكني متطور في أرتل.',
                'purpose' => 'sale',
                'type' => 'land',
                'price' => 93000000,
                'currency' => 'YER',
                'area_m2' => 320,
                'bedrooms' => null,
                'bathrooms' => null,
                'address' => 'أرتل، صنعاء',
                'latitude' => 15.3961000,
                'longitude' => 44.2418000,
            ],
            [
                'title' => 'أرض للبيع في سعوان',
                'description' => 'قطعة أرض قريبة من الشارع العام في سعوان.',
                'purpose' => 'sale',
                'type' => 'land',
                'price' => 110000000,
                'currency' => 'YER',
                'area_m2' => 350,
                'bedrooms' => null,
                'bathrooms' => null,
                'address' => 'سعوان، صنعاء',
                'latitude' => 15.3939000,
                'longitude' => 44.2264000,
            ],
            [
                'title' => 'أرض للبيع في حزيز',
                'description' => 'أرض مناسبة لمشروع سكني صغير.',
                'purpose' => 'sale',
                'type' => 'land',
                'price' => 46000000,
                'currency' => 'YER',
                'area_m2' => 280,
                'bedrooms' => null,
                'bathrooms' => null,
                'address' => 'حزيز، صنعاء',
                'latitude' => 15.2994000,
                'longitude' => 44.2145000,
            ],
            [
                'title' => 'محل للإيجار في التحرير',
                'description' => 'محل تجاري في منطقة حيوية مناسب لمختلف الأنشطة.',
                'purpose' => 'rent',
                'type' => 'shop',
                'price' => 280000,
                'currency' => 'YER',
                'area_m2' => 55,
                'bedrooms' => null,
                'bathrooms' => 1,
                'address' => 'التحرير، صنعاء',
                'latitude' => 15.3521000,
                'longitude' => 44.2069000,
            ],
            [
                'title' => 'محل للبيع في شارع الزبيري',
                'description' => 'محل تجاري بواجهة مباشرة على شارع نشط.',
                'purpose' => 'sale',
                'type' => 'shop',
                'price' => 95000000,
                'currency' => 'YER',
                'area_m2' => 70,
                'bedrooms' => null,
                'bathrooms' => 1,
                'address' => 'شارع الزبيري، صنعاء',
                'latitude' => 15.3547000,
                'longitude' => 44.1968000,
            ],
            [
                'title' => 'مكتب للإيجار في شارع الجزائر',
                'description' => 'مكتب مجهز في موقع مركزي مناسب للشركات.',
                'purpose' => 'rent',
                'type' => 'office',
                'price' => 320000,
                'currency' => 'YER',
                'area_m2' => 95,
                'bedrooms' => null,
                'bathrooms' => 2,
                'address' => 'شارع الجزائر، صنعاء',
                'latitude' => 15.3508000,
                'longitude' => 44.1889000,
            ],
            [
                'title' => 'مكتب للبيع في حدة',
                'description' => 'مكتب إداري حديث في منطقة حدة.',
                'purpose' => 'sale',
                'type' => 'office',
                'price' => 78000000,
                'currency' => 'YER',
                'area_m2' => 110,
                'bedrooms' => null,
                'bathrooms' => 2,
                'address' => 'حدة، صنعاء',
                'latitude' => 15.3461000,
                'longitude' => 44.1823000,
            ],
            [
                'title' => 'مزرعة للبيع شمال صنعاء',
                'description' => 'مزرعة صغيرة مع أرض زراعية ومدخل مستقل.',
                'purpose' => 'sale',
                'type' => 'farm',
                'price' => 185000000,
                'currency' => 'YER',
                'area_m2' => 1800,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'address' => 'شمال صنعاء',
                'latitude' => 15.4562000,
                'longitude' => 44.1768000,
            ],
            [
                'title' => 'شقة للإيجار في صنعاء القديمة',
                'description' => 'شقة بطابع يمني قريب من الأسواق التاريخية.',
                'purpose' => 'rent',
                'type' => 'apartment',
                'price' => 180000,
                'currency' => 'YER',
                'area_m2' => 105,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'address' => 'صنعاء القديمة',
                'latitude' => 15.3558000,
                'longitude' => 44.2143000,
            ],
            [
                'title' => 'منزل للبيع في شارع تعز',
                'description' => 'منزل سكني للبيع بالقرب من شارع تعز.',
                'purpose' => 'sale',
                'type' => 'house',
                'price' => 87000000,
                'currency' => 'YER',
                'area_m2' => 220,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'address' => 'شارع تعز، صنعاء',
                'latitude' => 15.3266000,
                'longitude' => 44.2052000,
            ],
            ];

            $imagePaths = [
                'demo-properties/property-exterior.png',
                'demo-properties/property-interior.png',
                'demo-properties/property-location.png',
            ];

            foreach ($rows as $row) {
                DB::table('properties')->updateOrInsert(
                    ['title' => $row['title']],
                    array_merge($row, [
                        'user_id' => $userId,
                        'status' => 'published',
                        'updated_at' => now(),
                    ]),
                );

                $propertyId = DB::table('properties')
                    ->where('title', $row['title'])
                    ->value('id');

                DB::statement(
                    'UPDATE properties
                     SET location = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
                     WHERE id = ?',
                    [$propertyId],
                );

                if (Schema::hasTable('property_images')) {
                    foreach ($imagePaths as $sortOrder => $path) {
                        DB::table('property_images')->updateOrInsert(
                            [
                                'property_id' => $propertyId,
                                'path' => $path,
                            ],
                            [
                                'cdn_url' => $path,
                                'sort_order' => $sortOrder,
                                'is_primary' => $sortOrder === 0,
                                'updated_at' => now(),
                            ],
                        );
                    }
                }
            }
        });
    }
}
