import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/network/api_error_message.dart';
import '../data/property_request_repository.dart';
import '../domain/property_request_models.dart';
import 'property_request_form_screen.dart';

class PropertyRequestDetailsScreen extends ConsumerStatefulWidget {const PropertyRequestDetailsScreen({super.key,required this.id,this.researcher=false});final int id;final bool researcher;@override ConsumerState<PropertyRequestDetailsScreen> createState()=>_State();}
class _State extends ConsumerState<PropertyRequestDetailsScreen>{late Future<PropertyRequestModel> future;@override void initState(){super.initState();future=_load();}Future<PropertyRequestModel> _load()=>widget.researcher?ref.read(propertyRequestRepositoryProvider).researcherShow(widget.id):ref.read(propertyRequestRepositoryProvider).show(widget.id);void refresh()=>setState(()=>future=_load());
 @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('تفاصيل طلب العقار')),body:FutureBuilder(future:future,builder:(context,snapshot){if(snapshot.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(snapshot.hasError)return Center(child:Text(friendlyApiError(snapshot.error!)));final r=snapshot.data!;return ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${r.operationType=='sale'?'شراء':'إيجار'} • ${r.propertyType}',style:Theme.of(context).textTheme.titleLarge),Text('${r.governorate}${r.district==null?'':' • ${r.district}'}${r.area==null?'':' • ${r.area}'}'),Text('الميزانية: ${r.budgetMin.toStringAsFixed(0)} - ${r.budgetMax.toStringAsFixed(0)} ${r.currency}'),if(r.requestedAreaMin!=null||r.requestedAreaMax!=null)Text('المساحة: ${r.requestedAreaMin??'-'} - ${r.requestedAreaMax??'-'} م²'),if(r.rooms!=null)Text('الغرف: ${r.rooms}'),if(r.additionalSpecifications!=null)Text(r.additionalSpecifications!),Text('الحالة: ${r.status}')]))),if(widget.researcher)..._researcher(r)else..._owner(r)]);})));
 List<Widget> _owner(PropertyRequestModel r)=>[if(r.canEdit)OutlinedButton(onPressed:()async{await Navigator.of(context).push(MaterialPageRoute(builder:(_)=>PropertyRequestFormScreen(request:r)));refresh();},child:const Text('تعديل الطلب')),if(r.canClose)FilledButton.tonal(onPressed:()async{await ref.read(propertyRequestRepositoryProvider).close(r.id);ref.invalidate(myPropertyRequestsProvider);refresh();},child:const Text('إغلاق الطلب')),const Padding(padding:EdgeInsets.symmetric(vertical:12),child:Text('العقارات المقترحة',style:TextStyle(fontWeight:FontWeight.bold,fontSize:18))),...r.suggestions.map((s)=>Card(child:ListTile(title:Text(s.property?.title??'عقار مقترح'),subtitle:Text(s.note??'اقترحه ${s.suggestedByName}'),trailing:const Icon(Icons.chevron_left),onTap:()=>context.push('/properties/${s.propertyId}'))))];
 List<Widget> _researcher(PropertyRequestModel r)=>[const Padding(padding:EdgeInsets.symmetric(vertical:12),child:Text('عقاراتي المطابقة والمنشورة',style:TextStyle(fontWeight:FontWeight.bold,fontSize:18))),...r.eligibleProperties.map((p)=>Card(child:ListTile(title:Text(p.title),subtitle:Text('${p.price.toStringAsFixed(0)} ${p.currency}'),trailing:FilledButton(onPressed:()=>_suggest(r.id,p),child:const Text('اقتراح')))))];
 Future<void> _suggest(int requestId,SuggestableProperty p)async{try{await ref.read(propertyRequestRepositoryProvider).suggest(requestId,p.id);if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم إرسال الاقتراح وإشعار الباحث.')));context.push('/properties/${p.id}');}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyApiError(e))));}}
}
