import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/network/api_error_message.dart';
import '../data/property_request_repository.dart';
import '../domain/property_request_models.dart';

class PropertyRequestFormScreen extends ConsumerStatefulWidget { const PropertyRequestFormScreen({super.key,this.request});final PropertyRequestModel? request;@override ConsumerState<PropertyRequestFormScreen> createState()=>_State();}
class _State extends ConsumerState<PropertyRequestFormScreen>{final _form=GlobalKey<FormState>();late String operation,type;late final Map<String,TextEditingController> c;bool saving=false;@override void initState(){super.initState();final r=widget.request;operation=r?.operationType??'sale';type=r?.propertyType??'apartment';c={'governorate':TextEditingController(text:r?.governorate),'district':TextEditingController(text:r?.district),'area':TextEditingController(text:r?.area),'budget_min':TextEditingController(text:r?.budgetMin.toString()),'budget_max':TextEditingController(text:r?.budgetMax.toString()),'requested_area_min':TextEditingController(text:r?.requestedAreaMin?.toString()),'requested_area_max':TextEditingController(text:r?.requestedAreaMax?.toString()),'rooms':TextEditingController(text:r?.rooms?.toString()),'additional_specifications':TextEditingController(text:r?.additionalSpecifications),'active_duration_days':TextEditingController(text:(r?.activeDurationDays??30).toString())};} @override void dispose(){for(final x in c.values)x.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(widget.request==null?'طلب عقار جديد':'تعديل الطلب')),body:Form(key:_form,child:ListView(padding:const EdgeInsets.all(16),children:[DropdownButtonFormField(value:operation,decoration:const InputDecoration(labelText:'نوع العملية'),items:const [DropdownMenuItem(value:'sale',child:Text('شراء')),DropdownMenuItem(value:'rent',child:Text('إيجار'))],onChanged:(v)=>setState(()=>operation=v!)),DropdownButtonFormField(value:type,decoration:const InputDecoration(labelText:'نوع العقار'),items:const ['apartment','house','villa','land','shop','office','farm'].map((v)=>DropdownMenuItem(value:v,child:Text(v))).toList(),onChanged:(v)=>setState(()=>type=v!)),...['governorate','district','area','budget_min','budget_max','requested_area_min','requested_area_max','rooms','additional_specifications','active_duration_days'].map((key)=>Padding(padding:const EdgeInsets.only(top:12),child:TextFormField(controller:c[key],keyboardType=['budget_min','budget_max','requested_area_min','requested_area_max','rooms','active_duration_days'].contains(key)?TextInputType.number:null,maxLines:key=='additional_specifications'?3:1,decoration:InputDecoration(labelText:_label(key),border:const OutlineInputBorder()),validator:(v)=>['governorate','budget_min','budget_max','active_duration_days'].contains(key)&&(v==null||v.trim().isEmpty)?'مطلوب':null))),const SizedBox(height:20),FilledButton(onPressed:saving?null:_save,child:Text(saving?'جارٍ الحفظ...':'حفظ الطلب'))]))));
  String _label(String k)=>{'governorate':'المحافظة','district':'المديرية','area':'المنطقة','budget_min':'الميزانية الدنيا','budget_max':'الميزانية العليا','requested_area_min':'المساحة الدنيا (م²)','requested_area_max':'المساحة العليا (م²)','rooms':'الغرف','additional_specifications':'مواصفات إضافية','active_duration_days':'مدة النشاط بالأيام'}[k]!;
  int? _int(String k)=>c[k]!.text.trim().isEmpty?null:int.tryParse(c[k]!.text.trim());double? _double(String k)=>double.tryParse(c[k]!.text.trim());String? _text(String k)=>c[k]!.text.trim().isEmpty?null:c[k]!.text.trim();
  Future<void> _save()async{if(!_form.currentState!.validate())return;setState(()=>saving=true);try{final data={'operation_type':operation,'property_type':type,'governorate':c['governorate']!.text.trim(),'district':_text('district'),'area':_text('area'),'budget_min':_double('budget_min'),'budget_max':_double('budget_max'),'currency':'YER','requested_area_min':_int('requested_area_min'),'requested_area_max':_int('requested_area_max'),'rooms':_int('rooms'),'additional_specifications':_text('additional_specifications'),'active_duration_days':_int('active_duration_days')};final repo=ref.read(propertyRequestRepositoryProvider);widget.request==null?await repo.create(data):await repo.update(widget.request!.id,data);ref.invalidate(myPropertyRequestsProvider);if(mounted)context.pop();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyApiError(e))));}finally{if(mounted)setState(()=>saving=false);}}
}
